In [6]:
#Numpy Array 

import numpy as np
a = np.array([1,2,3,4])
b = np.array([234,23,2,34])


In [7]:
a

array([1, 2, 3, 4])

In [8]:
a*2

array([2, 4, 6, 8])

In [9]:
A=a+b

In [10]:
A

array([235,  25,   5,  38])

# Array Cration


In [19]:
np.array([1,2,3])

array([1, 2, 3])

In [20]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [23]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Shape, Dimension, Datatype

In [25]:
a = np.array([[1,2,3],[4,5,6]])

a.shape      # (2,3)



(2, 3)

In [26]:
a.ndim       # 2


2

In [27]:
a.dtype      # int64


dtype('int32')

In [28]:
a.size       # 6

6

# Indexing & Slicing

In [29]:
a[0,1] 

2